import { StyleSheet } from "react-native";

const stylesApp = StyleSheet.create({
  logoFotterName: { fontSize: 10, fontWeight: "900", color: "#707B81" },
  inputContainerStyle: {
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 29,
    height: "50%",
    width: "90%",
  },
  containerStyle: {
    backgroundColor: "#F5F8FA",
    height: "10.49%",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    borderTopColor: "transparent",
    borderBottomColor: "#DAE0E3",
    borderBottomWidth: 0.3,
    borderTopWidth: 0.3,
  },

  logo: {
    height: "20%",
    width: "20%",
    alignItems: "center",
    justifyContent: "center",
  },
  searchBar: {
    height: "10.49%",
    width: "100%",
    backgroundColor: "#F5F8FA",
    borderColor: "#DAE0E3",
    borderBottomWidth: 0.3,
    borderTopWidth: 0,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: "0%",
    paddingBottom: "10%",
  },
  scroll: {
    height: "72%",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#DAE0E3",
    borderWidth: 0.3,
  },
  footer: {
    backgroundColor: "#FFFFFF",
    height: "10.04%",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#DAE0E3",
    borderWidth: 0.3,
    flexDirection: "row",
    justifyContent: "space-between",
    position: "relative",
  },
  titulo: {
    color: "#121212",
    fontSize: 50,
    width: "100%",
    paddingHorizontal: 70,
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  headerBar: {
    height: "8%",
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  logoBackHeader: {
    height: "100%",
    width: "20%",
    marginLeft: "20%",
    marginRight: 0,
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
  },
  headerButton: {
    height: "100%",
    width: "100%",
    backgroundColor: "#FFFFFF",
    alignItems: "flex-end",
    marginRight: "5%",
    flexDirection: "row",
  },
});

export default stylesApp;
