export const color = {
  PRIMARY: '#6F4DBF',
  SECONDARY: '#40C5D6',
  BLACK: '#627179',
  BACKGROUND: '#ECF0F2',
  WARNING: '#E85D1F',
  GREEN: '#AED335',
  WHITE: '#FFF',
  BORDER: '#DAE0E3',
};

export const colorLight = {
  PRIMARY: '#6F4DBF',
  SECONDARY: '#818181',
  BLACK: '#AAAFB2',
  BACKGROUND: '#ECF0F2',
  WARNING: '#AAAFB2',
  GREEN: '#AAAFB2',
  WHITE: '#F7F8F8',
  BORDER: '#DAE0E3',
};
