export { default as IconAction } from './icon_actions.svg';
export { default as IconPensionMoney } from './icon_pension_money.svg';
export { default as IconWalletSmall } from './icon_wallet_small.svg';
export { default as IconArrowLeft } from './icon_arrow_left.svg';
export { default as IconFavorite } from './icon_favorite.svg';
export { default as IconFavoriteActive } from './icon_favorite_active.svg';
export { default as IconLivreDown } from './icon_livre_down.svg';
export { default as IconLoad } from './icon_load.svg';
export { default as IconArrowUp } from './icon_arrow_up.svg';
