export const FundsSections = [
  {
    id: 1,
    name: 'Alaska Black Institucional Fundo de Investimento de Ações',
    type: 'FIA',
    minimumValue: 500,
    rating: 0,
    profitability: -52.05,
    status: 0,
  },
  {
    id: 2,
    name: 'BNP Paribas Inflação FI RF',
    type: 'RF',
    minimumValue: 300,
    rating: 2,
    profitability: 20.24,
    status: 1,
  },
  {
    id: 3,
    name: 'Selection Long Biased Fundo de Investimento',
    type: 'Multimercado',
    minimumValue: 100,
    rating: 4,
    profitability: -7.12,
    status: 0,
  },
  {
    id: 4,
    name: 'CAIXA FIA Institucional BDR Nível I',
    type: 'FIA',
    minimumValue: 750,
    rating: 4,
    profitability: 0,
    status: 2,
  },
  {
    id: 5,
    name: 'CSN INVEST FUNDO DE INVESTIMENTO EM AÇÕES',
    type: 'FIA',
    minimumValue: 100,
    rating: 3,
    profitability: 20.5,
    status: 2,
  },
];
