export const PensionSections = [
  {
    id: 1,
    name: 'Adam XP Seg Prev I FIC FIM',
    type: 'Multimercados',
    minimumValue: 100.0,
    tax: 0,
    redemptionTerm: 10,
    profitability: 10.59,
  },
  {
    id: 2,
    name: 'Brasil Capital 100 XP Seg Advisory FIC FIA',
    type: 'Multimercados',
    minimumValue: 100.0,
    tax: 0,
    redemptionTerm: 2,
    profitability: -7.05,
  },
  {
    id: 3,
    name: 'Capitânia Prev Advisory XP Seg FIRF CP',
    type: 'Renda Fixa Pós',
    minimumValue: 300.0,
    tax: 2.67,
    redemptionTerm: 1,
    profitability: 5.12,
  },
  {
    id: 4,
    name: 'Icatu Seg Kadima FIM CP Prev',
    type: 'Multimercados',
    minimumValue: 400.0,
    tax: 0.45,
    redemptionTerm: 5,
    profitability: 19.26,
  },
  {
    id: 5,
    name: 'XP Horizonte XP Seg FIRF Prev',
    type: 'Renda Fixa Pré',
    minimumValue: 500.0,
    tax: 0,
    redemptionTerm: 1,
    profitability: 0,
  },
];
