export {default as Profit} from './Profit'
export {default as ProfitIcon} from './ProfitIcon'
export {default as ProfitText} from './ProfitText'
export {default as WisheIcon} from './WisheIcon'
export {default as StarIcon} from './StarIcon'
export {default as Label} from './Label'